### ISSUE TITLE
Mutliple GW control

### ISSUE THREAD

**Issue by arist0v** [WebThingsIO/android-app#26]
As a user i would like to be able to control multiple gateway from the same app

**Comment by benfrancis** [comment]
I agree with this. A gateway should act as a WoT Directory, so the way to add multiple gateways is to add them as directories using the URL of their Directory Description (a Thing Description for directories). I've added a [comment](https://github.com/WebThingsIO/android-app/issues/13#issuecomment-1104937052) to #13 to make this more clear and am closing this issue as a duplicate of that one.
